project:
  type: website

website:
  title: "JieShuang' blog"
  open-graph: true
  twitter-card: true
  search:
    keyboard-shortcut: ["/"]
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/nlimpid
      - icon: twitter
        href: https://x.com/nlimpid
      - icon: rss
        href: index.xml

include-in-header:
  file: cloudflare.html

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
