name: CI

on: [push]

jobs:
  first:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
        with:
          submodules: true
          ref: master
          clean: false
      - name: hugo build
        uses: ./.github/actions/build
      - name: push to remote
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: ./publish.sh