name: CI

on: [push]

jobs:
  first:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
        with:
          submodules: True
      - name: hugo build
        uses: ./.github/actions/build
      - name: push to remote
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./publish.sh