name: CI

on: [push]

jobs:
  first:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
        with:
          submodules: True
      - uses: actions/setup-go@master
      - name: hugo build
        uses: ./.github/actions/build
